export const teamCandidateSeed = [
  {
    id: "SP-201",
    name: "مریم شریفی",
    title: "طراحی محصول و نمونه‌سازی",
    expertise: "طراحی و ساخت",
    evidenceRank: 92,
    city: "تهران",
    university: "دانشگاه تهران",
    collaborations: ["حضوری", "پروژه‌ای"],
    skills: ["پایلوت صنعتی", "نمونه‌سازی"],
    availability: "۱۸ ساعت در هفته",
    projects: "۴ پروژه صنعتی تأییدشده",
  },
  {
    id: "SP-202",
    name: "رضا اکبری",
    title: "برق، کنترل و ابزار دقیق",
    expertise: "برق و کنترل",
    evidenceRank: 88,
    city: "اصفهان",
    university: "دانشگاه صنعتی اصفهان",
    collaborations: ["حضوری", "پروژه‌ای"],
    skills: ["تحلیل مسئله", "کنترل صنعتی"],
    availability: "۱۲ ساعت در هفته",
    projects: "۳ پروژه صنعتی تأییدشده",
  },
  {
    id: "SP-203",
    name: "نگار محمدی",
    title: "تحلیل داده و یادگیری ماشین",
    expertise: "داده و هوش مصنوعی",
    evidenceRank: 84,
    city: "دورکار",
    university: "دانشگاه صنعتی امیرکبیر",
    collaborations: ["دورکار", "پروژه‌ای"],
    skills: ["همکاری تیمی", "یادگیری ماشین"],
    availability: "۲۰ ساعت در هفته",
    projects: "۵ پروژه داده‌محور تأییدشده",
  },
  {
    id: "SP-204",
    name: "پویان رستگار",
    title: "مدیریت پایلوت صنعتی",
    expertise: "مدیریت و عملیات",
    evidenceRank: 79,
    city: "کرج",
    university: "دانشگاه علم و صنعت ایران",
    collaborations: ["حضوری", "تمام‌وقت"],
    skills: ["تحویل فنی", "مدیریت پروژه"],
    availability: "تمام‌وقت پروژه",
    projects: "۶ پایلوت صنعتی تأییدشده",
  },
];

export type TeamCandidate = (typeof teamCandidateSeed)[number];
